version: '3'
services:
  waha-plus--mongodb:
    # Check available Docker images:
    # https://waha.devlike.pro/docs/how-to/engines/#docker-images
    image: devlikeapro/waha-plus:latest
    container_name: waha-plus--mongodb
    ports:
      - '3001:3000/tcp'
    volumes:
      - './.sessions:/app/.sessions'
    environment:
      # Environment variables from https://waha.devlike.pro/docs/how-to/config/
      - WHATSAPP_RESTART_ALL_SESSIONS=True
      - WHATSAPP_HOOK_URL=https://sac-gpt.herokuapp.com
      - WHATSAPP_HOOK_EVENTS=message,session.status
      - WHATSAPP_API_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSHVtYW5vaWRlIn0.rroyrq29CEa883aWmiRQewPUtufYX8qkI99j3k64MS0
      - WHATSAPP_SWAGGER_USERNAME=admin
      - WHATSAPP_SWAGGER_PASSWORD=123
      - WAHA_DASHBOARD_USERNAME=admin
      - WAHA_DASHBOARD_PASSWORD=123
      - WHATSAPP_API_HOSTNAME=localhost
      - WHATSAPP_DEFAULT_ENGINE=NOWEB
      - WHATSAPP_SESSIONS_MONGO_URL=mongodb://mongodb:27017
    restart: always

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017/tcp'
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data: {}
