development:
  adapter: postgresql
  host: localhost
  user: postgres
  password: postgres
  database: sac_gpt_database_development
  pool: 10
  timeout: 5000

test:
  adapter: postgresql
  host: localhost
  user: postgres
  password: postgres
  database: sac_gpt_database_test
  pool: 10
  timeout: 5000

production:
  adapter: postgresql
  database: sac_gpt_database_production
  pool: 10
  timeout: 5000
